2024-04-02 17:50:51,878 - INFO] DVC training
2024-04-02 17:50:51,878 - INFO] config :
2024-04-02 17:50:51,880 - INFO] {
    "tot_epoch": 10000,
    "tot_step": 2000000,
    "train_lambda": 1024,
    "lr": {
        "base": 0.0001,
        "decay": 0.1,
        "decay_interval": 1800000
    }
}
Traceback (most recent call last):
  File "main_dvc.py", line 292, in <module>
    os.mkdir('./events/{}'.format(save_name))
FileNotFoundError: [Errno 2] No such file or directory: './events/DVC_1024'